# Generated by Django 3.2.9 on 2022-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.domain')),
            ],
        ),
    ]
