# Generated by Django 3.2.9 on 2022-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20220409_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authorized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
