# Generated by Django 3.2.9 on 2022-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20220409_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authorized',
            field=models.ManyToManyField(blank=True, null=True, to='metadata.Domain'),
        ),
    ]
