# Generated by Django 3.2.9 on 2022-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20220410_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
