# Generated by Django 3.2.9 on 2022-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='sender',
            field=models.TextField(unique=True),
        ),
    ]
