# Generated by Django 3.2.9 on 2022-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_alter_sender_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sender',
            name='sender',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
