# Generated by Django 3.2.9 on 2022-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20220411_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authorized',
            field=models.ManyToManyField(blank=True, to='metadata.Account'),
        ),
    ]
