# Generated by Django 3.2.9 on 2022-04-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_alter_account_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authorized',
            field=models.ManyToManyField(blank=True, null=True, to='metadata.Account'),
        ),
    ]
