# Generated by Django 3.2.9 on 2022-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
