# Generated by Django 3.2.9 on 2022-04-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reachable',
            field=models.BooleanField(default=False),
        ),
    ]
