# Generated by Django 3.2.9 on 2022-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0018_account_reachable'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authorizeWebhook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
